version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta de comunicação do RabbitMQ
      - "15672:15672"  # Porta do painel de administração
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fakestore-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: FakeStoreProducts.Worker/Dockerfile
    container_name: fakestore-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Production
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    networks:
      - fakestore-network
    restart: on-failure

networks:
  fakestore-network:
    driver: bridge

volumes:
  rabbitmq_data: